image: lyriclitest/swift:5.0.1

stages:
  - lint

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  paths:
    - .build/

lint:
  stage: lint
  script:
    - make lint

document:
  stage: document
  script:
    - make document
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  script:
    - mv docs public
  artifacts:
    paths:
      - public
